### ISSUE TITLE
Mogrify's -format option

### ISSUE THREAD

**Issue by foaly-nr1** [snowcap/SnowcapImBundle#24]
From the ImageMagick docs:
> This tool is similar to convert except that the original image file is overwritten (unless you change the file suffix with the -format option) with any changes you request.

So for the following config, mogrify will fail if the source image is of a different format:

```yaml
snowcap_im:
    formats:
        default:
            format: jpeg
```

It is possible that this is related to the issue https://github.com/snowcap/SnowcapImBundle/issues/21.

Will create a PR if I get round to it.
