### ISSUE TITLE
ClassNotFoundException on convert

### ISSUE THREAD

**Issue by codingcreature** [snowcap/SnowcapImBundle#29]
I installed version 2.0.4 and every time I call method **convert** I get following exception:
```
Attempted to load class "MetadataFactory" from namespace "Metadata".
Did you forget a "use" statement for another namespace?
```
In version 2.0.3 it worked. 

While debugging I noticed that in your service.yml you refer to classes (**FileCache**, **MetadataFactory**), which do not exist in your code:

```
 snowcap_im.metadata.cache:
        class: Metadata\Cache\FileCache
        public: false
        arguments:
            - {}

    snowcap_im.metadata.mogrify_factory:
        class: Metadata\MetadataFactory
        public: false
        arguments: [@snowcap_im.metadata.mogrify_driver]
        calls:
            - [setCache, ["@snowcap_im.metadata.cache"]]
```
